name: asocombeima
description: Aplicación de monitoreo de Asocombeima

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.10.0'

dependencies:
  flutter:
    sdk: flutter
  postgres: ^2.5.2
  flutter_session_manager: ^1.0.3
  flutter_excel: ^1.0.1
  path_provider: ^2.0.11
  gsheets: ^0.4.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.10.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/asocombeima_Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/asocombeima_Logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/asocombeima_Logo.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.png
    - assets/images/asocombeima_Logo.png
  fonts:
    - family: Libre Franklin
      fonts:
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Regular.ttf
        - asset: assets/fonts/Libre_Franklin/LibreFranklin-Bold.ttf
          weight: 700